### ISSUE TITLE
Use IncrementalDomRenderer instead of Soy

### ISSUE THREAD

**Issue by mairatma** [metal/metal-router#1]
That's important so this component doesn't depend on a specific template (which would come with its own dependencies), and it's contents are so simple that there's no need for a template at all. For example, projects using JSX templates shouldn't need to include soy dependencies.

**Comment by eduardolundgren** [comment]
:+1:

**Comment by mairatma** [comment]
Just FYI, I didn't just remove soy completely from this repo, since that way components wouldn't be able to call `Router` inside soy files anymore, as it wouldn't have a soy template.

Instead I separate `Router` into two files, one that doesn't depend on soy, and another that does. Components that don't use soy can use the default `Router`, while soy components should import `RouterSoy` instead so they can have access to the template.

@eduardolundgren, can you update dashboard to make sure this doesn't break anything there? You basically just need to update calls to `import from 'metal-router'` to be `import from 'metal-router/src/RouterSoy'`. I could also break this into two repos if you prefer so that you could instead do something like: `import from 'metal-router-soy`.
