### ISSUE TITLE
Wait until data is fetched before rendering router component

### ISSUE THREAD

**Issue by mairatma** [metal/metal-router#10]
If the developer specified that the component's data should be fetched, then we need to wait for that data to be ready before rendering, otherwise we'll render a wrong version first (or even end up removing everything from the dom while the fetch is happening, which is bad for progressive enhancement).

**Comment by eduardolundgren** [comment]
It should be like that already due  to promise chaining. Could you provide more details?

**Comment by mairatma** [comment]
The problem is that we were always waiting to render the content, not only when data was a promise or fetch was true, but even when we had the data ready too. When we created a `Router` component, it's `render` function is ran, but it skipped rendering completely (which in turn removed any received `element` from the dom, making progressive enhancement not work at all). It only got rendered after a senna `dispatch` call, which is the one that causes our screen to match the right router to the current url and finally render for the first time. This can be async though (specially when `fetch` is true) and so the content gets removed before being rendered by the router again.

Last Friday I changed the Router so that it would always match itself with the current url on the first render, to avoid this problem. I had to skip this for the case where we have to fetch data though, so it's still not working as it should. This change I made on Friday was just temporary so that I could unblock @brunobasto, who was having problems with it, but today I'll make sure to update the code to handle all these cases better (making sure that we don't lose the element instance if we're waiting to fetch data for example).

**Comment by eduardolundgren** [comment]
That's why we had the concept of `initialState` so then the initial state can be printed from the server without requiring asynchronously fetching it on the first load, then the following navigations will fetch them. Do we still have it?

**Comment by mairatma** [comment]
We do, it's named `data` now (since it can be used for later states too, not just the initial one), but that's also the one that can be a promise, and can also not be given at all. So basically I just need to make sure we can handle the case where there's no initial state, just an async fetch, while making sure that we won't remove anything from the dom until the router is ready to render over it.
