### ISSUE TITLE
Pass extracted params to route data function

### ISSUE THREAD

**Issue by Robert-Frampton** [metal/metal-router#11]
Currently only the `path` is passed to the data function.

```js
Component.render(Router, {
    data: (path) => {
        // path == 'entry/1234'
    },
    element: '#container',
    path: '/entry/:id(\\w+)?',
    component: Entry
});
```

However, I'd like to use the id in a request to an external db, but I don't want to manually parse the path for the id. I can retrieve the `route` and then use the `extractParams` method, but it feels verbose.

```js
Component.render(Router, {
    data: (path) => {
        const params = Router.router().findRoute(path).extractParams(path);
    },
    element: '#container',
    path: '/entry/:id(\\w+)?',
    component: Entry
});
```

It would be nice to have the extracted params passed to the data function as the second argument.

**Comment by mairatma** [comment]
Good suggestion, will do.
