### ISSUE TITLE
Sets support to route matching ignore query string from path by default

### ISSUE THREAD

**Issue by eduardolundgren** [metal/metal-router#16]
This can be achieved by enabling by default on metal-router this option from Senna:
https://github.com/liferay/senna.js/blob/master/src/app/App.js#L85

Any objections for the change?

**Comment by bawachhe** [comment]
I don't think we use querystrings anywhere, only friendlyURLs; and our json urls use POST data, so I think it'd be ok.  Can you sanity-check me, @ssmith353 ?

**Comment by ssmith353** [comment]
@bawachhe, yeah. we aren't using any query strings at the moment, but we might when we implement search?

**Comment by bawachhe** [comment]
As long as this doesn't clear the query string, it'd probably still be ok, since I don't think we're planning on changing the way things are routed based on the query string.

**Comment by mairatma** [comment]
Exactly, good to know, then we can probably make this change, thanks!
