### ISSUE TITLE
Soy component lifecycle not executed when route added via JavaScript passing the component reference

### ISSUE THREAD

**Issue by eduardolundgren** [metal/metal-router#17]
If the route is added via JavaScript api to a soy component, e.g.:

```js
'use strict';

import templates from './Home.soy.js';
import Component from 'metal-component';
import Soy from 'metal-soy';

class Home extends Component {
	attached() {
		console.log('--> Home attached');
	}

	rendered() {
		console.log('--> Home rendered');
	}

	disposed() {
		console.log('--> Home disposed');
	}
}

Soy.register(Home, templates);

export default Home;
```

Adding the route by reference:

```js
import { Home } from './Home';
		
Component.render(Router, {
	element: '#main > div',
	component: Home // Note component is Home reference
});
```

When `Router.router().dispatch();` happens the lifecycle methods for `Home` are not called.

```
Navigate to [/demos/basic/]
Create screen for [/demos/basic/] [screen_1]
-> Navigating to /demos/basic/
Screen [screen_1] activate
Navigation done
-> Navigation done
```

On the other hand if it's mapped by the component name `"Home"` it works fine:

```js
import { Home } from './Home';
		
Component.render(Router, {
	element: '#main > div',
	component: 'Home' // Note component name is being used
});
```

```
Navigate to [/demos/basic/]
Create screen for [/demos/basic/] [screen_1]
-> Navigating to /demos/basic/
--> Home rendered
--> Home attached
Screen [screen_1] activate
Navigation done
-> Navigation done
```

**Comment by mairatma** [comment]
I've just tried this and it works as expected for me. At first it didn't but I noticed that my Chrome had automatically turned off the option of disabling cache when dev tools is open. That's probably why you couldn't see the logs as well, they probably did this in an update to everyone by mistake.

Once I disabled the cache again and added these logs I could see them running as usual. That makes sense since the lifecycle functions has nothing to do with the router or with incremental dom renderer, it's run by `Component`'s constructor, and so whenever you create a component, regardless of how you do it, they will run.

**Comment by eduardolundgren** [comment]
I also had some weird caching issues with Chrome today, so this all make sense. Although, I have tested it in Firefox and Safari and all behave the same - not logging it properly. To clarify I recorded a gif that shows the issue of not appearing the lifecyle logs on `/basic/` only on `/basic-soy/`.

![router](https://cloud.githubusercontent.com/assets/113087/21464465/80b22366-c932-11e6-8674-22c5e8d296e8.gif)

**Comment by eduardolundgren** [comment]
In case it helps this is my `/demos/build/metal.js` bundle file https://cl.ly/0d3V1r2J3322/metal.js.

**Comment by brunobasto** [comment]
I"m able to reproduce the issue too. `[demos/basic-soy]` logs properly, but `[demos/basic]` doesn't. Setting the component by name instead of by reference like mentioned above seems to solve the issue.

**Comment by brunobasto** [comment]
And changing https://github.com/metal/metal-router/blob/master/demos/src/Basic.js#L5 to `import Home from './Home';` seems to make it work. So looks like an issue with our named imports/exports.

Indeed the transpiled Home.soy ends up like this:

```
Soy.register(Home, templates);

this['metalNamed']['Home'] = this['metalNamed']['Home'] || {};
this['metalNamed']['Home']['Home'] = Home;
this['metalNamed']['Home']['templates'] = templates;
this['metal']['Home'] = templates;
```

While the transpiled Home.js onyl does:
```
Soy.register(Home, templates);

this['metal']['Home'] = Home;
```

**Comment by brunobasto** [comment]
And this makes sense since we are not doing named exports on the demo. I think it's just a problem with the demo then.

**Comment by eduardolundgren** [comment]
Good catch @brunobasto! :)
