### ISSUE TITLE
Add "types" to path matchers.

### ISSUE THREAD

**Issue by mthadley** [metal/metal-router#24]
Hey everyone, I wanted to throw out a quick idea that may reduce some of the boilerplate when defining our routes.

It's pretty common to define a route like this, possibly many times, that is meant to match some kind of `number`:

```jsx
<Route
  component={userPage}
  path="user/:id(\d+)/"
/>
```

After a while, it get's tedious to add these regexes to our routes, and also reduces readability. Maybe instead we could still allow for a regex, but also provide some default "types":

```jsx
<Route
  component={userPage}
  path="user/:id<number>/"
/>
```

The syntax is subject to change, but I think it would at least be useful for parsing numbers. Possible other things like booleans as well.

Thanks!

**Comment by jbalsas** [comment]
Hey @mthadley, this does indeed seem interesting, but I haven't been able to find a similar approach out there int he wild. All of them seem to just rely on regexes for this. 

I'd be more comfortable if there is already a pattern for this out there, so we don't need to come up with our own format. Do you know of any such cases?

**Comment by mthadley** [comment]
@jbalsas Yea! So Django recently added something like this. Check it out [here](https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax).

**Comment by Robert-Frampton** [comment]
This would actually mean changing Senna and https://github.com/metal/metal-path-parser.

@brunobasto, what are your thoughts on this behavior for the Senna `Route` class?

**Comment by jbalsas** [comment]
Moved to https://github.com/metal/metal-plugins/issues/13
