### ISSUE TITLE
Investigate demo bug where image stops being fetched correctly

### ISSUE THREAD

**Issue by mairatma** [metal/metal-router#3]
Steps to reproduce:
(1) Run and open the demo
(2) Click on "About"
(3) Click on "Home"

Expected result:
The home page is correctly rendered, with its image.

Actual result:
The home page is rendered, but the image isn't. See screenshot: 
<img width="543" alt="screen shot 2016-05-03 at 1 19 25 pm" src="https://cloud.githubusercontent.com/assets/5216049/14990202/e10d3f5c-1131-11e6-9ccb-1139a83d483a.png">

I believe that this is something on Senna.js's side, since this demo was working before, and the problem seems to be related to the image url being treated wrongly by the time the request is sent to fetch it. See error screenshot:
<img width="699" alt="screen shot 2016-05-03 at 1 21 34 pm" src="https://cloud.githubusercontent.com/assets/5216049/14990242/0fd58da8-1132-11e6-9dc3-72018527b193.png">

**Comment by mairatma** [comment]
This is very weird, I can't figure out why the browser would start trying to fetch the image from the wrong url like this. Note that it should be fetching from **http://localhost:8080/demos/basic/img/img1.jpg**, as it does on all other times. This problem only happens when going to the first **Home** link coming from a non home page.

At first I thought it could be something with the time of the rendering somehow being before the history transition completed or something like that, but even if I add an image element manually after this happens, the GET request is also wrong, and so also fails.

@eduardolundgren, do you have any idea what could be causing this? This repros on both Chrome and Firefox, so it's not a browser specific issue. One thing I've noticed is that this doesn't happen anymore if I move the **index.html** file to the root of **metal-router**, and update the routes accordingly.  It does seem like some bug with senna, though I don't know what it could be doing to cause this.

**Comment by eduardolundgren** [comment]
The at my side is that the python server is responding the wrong content type for the image on the second request:

![](http://cl.ly/3m3i023h0V1T/Screen%20Shot%202016-05-06%20at%209.16.00%20AM.png)

Note the `text/html` instead of `image/jpeg`. What server are you using to test?

**Comment by eduardolundgren** [comment]
It may be because the url is wrong, so then the content type comes as `text/html`.

**Comment by mairatma** [comment]
I've managed to repro this with just senna, so opened an issue there explaning the problem: https://github.com/liferay/senna.js/issues/131.
