### ISSUE TITLE
Simplify the process of running the demo

### ISSUE THREAD

**Issue by mairatma** [metal/metal-router#7]
It's currently hard to figure out how to run metal-router's demos. It's necessary to run a server on the project's root folder for things to work as expected. This is explained in the demo's README.md file, but people don't usually look at that.

We could instead explain this in the demo's initial page itself, so that it's more visible.

Also, would be nice to have an npm script that runs the server for the developer, so that they don't need to install and setup one themselves.

**Comment by fernandosouza** [comment]
This just happened to me. After running `npm install` and `gulp build` I've tried to run the demo through a Python static server and it didn't work. Fortunately, I found your explanation here and I took a look at the `README.md` file inside the demo/basic directory.

I think if this information were in the repository's README.md file could help. It's quite common devs look up for commands on repository's main page.

But we can try other options that could look weird or non-elegant:

1 - Commit all the demos files. 
2 - Run `npm build:demo` task right after `npm install` using `postinstall`
