### ISSUE TITLE
Add a way to customize the load url

### ISSUE THREAD

**Issue by mairatma** [metal/metal-router#8]
Users may use paths like **/books** in their app that should load a different url, like **/books.json** when `fetch` is `true`. We don't currently allow that, but it should be easy to do by just adding a state property to metal-router.

**Comment by eduardolundgren** [comment]
If you need a temporary work-around you can hook on https://github.com/liferay/senna.js/blob/master/src/screen/RequestScreen.js#L113 to customize the loading path behavior.

**Comment by mairatma** [comment]
Yes, good idea. Another option is to pass the `data` prop as a function that returns a promise, and does the fetch itself (in this case `fetch` shouldn't be `true`).

But once we have the option this will be easier to do :)

**Comment by mairatma** [comment]
I've just added a `fetchUrl` prop for this :)
